# Generated by Django 2.2.10 on 2020-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='subtotal',
            field=models.IntegerField(default=1),
        ),
    ]
